---
- name: Add identity key to authorized keys on host
  authorized_key: 
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and ssh_user is defined

- name: Disable empty password login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^#?PermitEmptyPasswords' 
    line: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Disable remote root login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^#?PermitRootLogin' 
    line: 'PermitRootLogin no'
  notify: restart sshd

- name: Disable password login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'
  when: 
    - add_identity_key is succeeded 
    - not add_identity_key is skipped
  notify: restart sshd

- name: Enable PAM
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^#?UsePAM' 
    line: 'UsePAM yes'
  notify: restart sshd
